spring.application.name=sbrestjpa0724
# 伺服器埠號（預設 8080）
server.port=8080

# MySQL 資料庫連線設定（請依據你的環境修改密碼）
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb?characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate 設定
# update , validate  , create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.column_ordering_strategy=legacy